[package]
name = "hetero-vec"
version = "0.1.0"
authors = ["Simon Vandel Sillesen <simon.vandel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"